
server: 
    port: 8081 #our service runs on port 8081. We are configuring it manually as of now, but should switch to automated config soon.
spring: 
    profiles:
        active: ${SPRING_PROFILES_ACTIVE}
---
spring:
    config:
        activate:
            on-profile:
                - local-dev
    session:
        store-type: ${STORE_TYPE}
    redis:
        port: ${STORE_TYPE_PORT:6379}
        host: ${STORE_TYPE_HOST}
    datasource:
        driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME}
        url: ${DATASOURCE_URL}
        username: ${DATASOURCE_USERNAME}
        password: ${DATASOURCE_PASSWORD} 
        platform: ${DATASOURCE_PLATFORM}
        initialization-mode:  ${DATASOURCE_INIT_MODE} ##not using embedded db for now. set this to get postgres db to init with data.sql
        hikari:
            schema: ${HIKARI_SCHEMA}
    application:
        ##our service will be registered as auth-service with consul. Any uri requiring authentication should have this at the 
        ## the api root /auth-service/employee/get... and etc, so that the gateway can perform the correct lookup.
        name: ${APPLICATION_NAME} 
    jpa:
        hibernate:
            ddl-auto: ${JPA_HIBERNATE_DDL_AUTO} ##create-drop setting for dev mode        
        properties:
            hibernate:
                    dialect: ${JPA_PROPERTIES_HIBERNATE_DIALECT}
                 

